# Generated by Django 4.1.2 on 2022-11-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_rename_user_data_customer_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='bookstore.customer'),
        ),
    ]
