# Generated by Django 4.1.2 on 2022-11-19 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_basket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(default=datetime.date(2022, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=24.55, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.DateField(default=datetime.date(1999, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinbasket',
            name='created',
            field=models.DateField(default=datetime.date(2020, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinbasket',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinbasket',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=6),
            preserve_default=False,
        ),
    ]
