# Generated by Django 4.1.2 on 2022-11-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_genre_description_alter_publisher_description_and_more'),
        ('bookstore', '0009_alter_basket_created_alter_basket_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference.serie'),
        ),
    ]
