# Generated by Django 4.1.2 on 2022-11-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='goods',
        ),
        migrations.AddField(
            model_name='basket',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='order_address1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='order_address2',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='order_city',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='order_country',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='order_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='order_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='basket',
            name='order_zip_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='bookstore.customer'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goodsinbasket', to='bookstore.basket'),
        ),
    ]
