# Generated by Django 4.1.2 on 2022-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_rename_number_goodsinbasket_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_status',
            field=models.CharField(choices=[('created', 'Created'), ('in_process', 'In Process'), ('done', 'Processed and delivered'), (' ', 'In doubt')], default=' ', max_length=20),
        ),
    ]
