# Generated by Django 4.1.2 on 2022-11-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_alter_book_available_alter_book_number_of_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinbasket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsinbasket', to='bookstore.basket'),
        ),
    ]
