# Generated by Django 4.1.2 on 2022-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_alter_basket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_status',
            field=models.CharField(choices=[('created', 'Created'), ('in_process', 'In Process'), ('done', 'Processed and delivered'), ('not_submitted', 'In doubt')], default='not_submitted', max_length=20),
        ),
    ]
