# Generated by Django 4.1.2 on 2022-11-27 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0021_alter_basket_customer_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order_phone'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_address1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order_address1'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_address2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order_address2'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order_city'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order_country'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_information',
            field=models.TextField(blank=True, null=True, verbose_name='order_information'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_status',
            field=models.CharField(choices=[('created', 'Created'), ('in_process', 'In Process'), ('done', 'Processed and delivered'), ('not_submitted', 'In doubt')], default='not_submitted', max_length=20, verbose_name='order_status'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='order_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order_zip_code'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(default='Yes', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='book',
            name='allowed_age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='allowed_age'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='book_format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=20, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number_of_pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.CharField(default=2022, max_length=4, verbose_name='publish_year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='address1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='address2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='zip_code'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='total_sum'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
    ]
