# Generated by Django 4.1.2 on 2022-11-28 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0022_alter_basket_contact_phone_alter_basket_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='comment_text')),
                ('rate', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='rate')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcomments', to='bookstore.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookcomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='comment_text')),
                ('rate', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='rate')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketcomments', to='bookstore.basket')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basketcomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
