# Generated by Django 4.1.2 on 2022-11-28 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0029_alter_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='rate'),
        ),
    ]
