# Generated by Django 4.1.2 on 2022-12-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0034_alter_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_status',
            field=models.CharField(choices=[('created', 'Created'), ('in_process', 'In Process'), ('done', 'Processed and delivered'), ('not_submitted', 'In doubt'), ('cancelled', 'Cancelled')], default='not_submitted', max_length=20, verbose_name='order_status'),
        ),
    ]
