# Generated by Django 4.1.1 on 2022-10-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover', models.CharField(max_length=20)),
                ('book_format', models.CharField(blank=True, max_length=20, null=True)),
                ('ISBN', models.CharField(max_length=30)),
                ('allowed_age', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default='Yes')),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.publisher')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.serie')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.book')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='Anonymous', max_length=100)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.goodsinbasket')),
            ],
        ),
    ]
