# Generated by Django 4.1.1 on 2022-10-10 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='goodsinbasket',
            name='updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
