# Generated by Django 4.1.2 on 2022-11-24 11:53

from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    content_type = ContentType.objects.get(app_label='auth', model='user')
    permission = Permission.objects.create(codename='registered_customer',
                                           name='Registered Customer',
                                           content_type=content_type)  # creating permissions
    group, created = Group.objects.get_or_create(name='Customers')
    group.permissions.add(permission)

    content_type = ContentType.objects.get(app_label='auth', model='user')
    permission = Permission.objects.create(codename='manager',
                                           name='Manager',
                                           content_type=content_type)  # creating permissions
    group, created = Group.objects.get_or_create(name='Managers')
    group.permissions.add(permission)

    content_type = ContentType.objects.get(app_label='auth', model='user')
    permission = Permission.objects.create(codename='admin',
                                           name='Admin',
                                           content_type=content_type)  # creating permissions
    group, created = Group.objects.get_or_create(name='Admin')
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions)
    ]

